### ISSUE TITLE
Log in and crush issues 

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#103]
- [x] Sometimes, the first-time login is taking much longer than expected. Login can keep going round endlessly and sometimes flagging an error related to internet connection even when the internet seems stable. (Question: are you able to see failed logging (Demo1) attempts on the server logs e.g.  in the 10th – 11th hour yesterday - Samsung galaxy tablet  - SM-T295).
 - [x]  On clicking register child, the tablet requests permission to “allow zeir to make and manage phone calls” If you allow, system crushes and if you deny, system doesn’t crush. (if this a device issue? @ellykits )

**Comment by ellykits** [comment]
Noted first time login takes about 15s and 5s average for subsequent login. The first time login takes more time because of other operations done after login including, saving downloaded server settings, updating opensrp user account in the device and saving of location hierarchy for the logged in user. If it takes longer than that then there maybe internet connection problems or server may not be responding to login requests. Do let us know if this persist and perhaps measure the login time for the next report.

**Comment by AnnieMungai** [comment]
@ellykits when I tried logging: Initial log in taking about 35-37sec on debug and 27sec on preview (yep, I timed it) 2nd login - 17sec. 
Can we be able to improve this time?

**Comment by AnnieMungai** [comment]
As this is not recurring, I will close the issue and open a performance improvement one.
