### ISSUE TITLE
ZEIR android users not able to log in

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#125]
In production, the app URL was switched over. Since the switch, users were not able to log on to the app. 

Could be related to [this issue](https://github.com/onaio/infrastructure/issues/3897), it is the only change that happened for users not to be able to log in.

**Comment by AnnieMungai** [comment]
The users can now log in to Keycloak and the app.

**Comment by tychus6** [comment]
The issue was resolved by hosting the Keycloak instance on the cloud(AWS)  while the  Open SRP server is deployed on premise. Since the hosting environments are different, this allowed OpenSRP to communicate with Keycloak instance.
However,this is a temporary fix, a long term fix is still required to resolve the issue of communication between Keycloak and OpenSRP hosted in the same  environment.
