### ISSUE TITLE
Immunizations data showing incorrect data

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#221]
Note: [Data dictionary](https://docs.google.com/spreadsheets/d/1_2xuIFr71IgqhWqI8Dwmu2BCR2gfD6LtgC2pJ030nTk/edit#gid=2010018538)
- [x] OPV0 - not showing outreach data. 
- [x] OPV 2, OPV3, IPV, Penta 3, RV 1 - showing only data for kids over 1 and not under 1.
- [x] RV 1 , RV 2 and PCV 1, Penta 1 - not picking any data. 
- [x] Labelling issue Penta 3 has a Penta 2 label on the draft report (confirm the correct label is on the daily tallies too!
Note! MR2 at outreach computed correctly. Let's replicate this for other indicators.
Issue edited!

**Comment by junaidwarsivd** [comment]
@AnnieMungai could you please reconfirm this in the new release because  according to the dictionary total number of children are for those children who are above 12 months and  the vaccine given in outreach and in the facility are for those children who are below 12 months this is mentioned in the labels as well  so for example  if the vaccine is given to the child that is above 1 year  weather in outreach or in the facility  Total  number  will increase ,  if the vaccine is given to the child below 12 months in the facility then (ABC given to children below < 12 months in facility) number will increase and same is applied for the outreach

**Comment by AnnieMungai** [comment]
v.0.0.27-debug
- [ ] Fully Immunized indicators not picking any data. 
- [ ] Vaccines given at the facility not reflecting any data.

**Comment by AnnieMungai** [comment]
v.0.0.27
Looks good. 

Usability:

Users MUST log out the app when switching between the outreaches and the facilities for the app to pick the correct data.
