### ISSUE TITLE
Vaccine relaxation to allow entry 5 days before it is due

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#5]
**Context**: Currently, the record vaccine button only becomes active the day the vaccine becomes due. This means the health worker cannot be able to record vaccines until they become due, even if the child visits the health facility a few days or hours to the vaccine due date. 
- [x] Relaxation of vaccine schedules to allow recording with 5 days before the due date as shown in this immunization schedule [here](https://docs.google.com/spreadsheets/d/1XjdrzwvJ4lm03mp59uyLYAvI-m2RxE0HFNjlDuq9e0w/edit#gid=0). 

- [x] **Enhancement**: The due dates for the vaccines remain the same as in the schedule. However, a user should be able to add vaccines 5 days or less, before the due date. The record vaccine button should become active 5 days before the vaccine due date. This means that if a child visits the health facility today, and their vaccines are due in 5 or less days, the health worker should still be able to record the vaccines that will become due in 5 days or less.

**Comment by cafootitt** [comment]
@AnnieMungai Is this how mastercard works? Does the button turn blue on the relaxation date? How many relaxation days does mastercard use?

**Comment by AnnieMungai** [comment]
@cafootitt, yes, the button turns blue on the relaxation date but the due date remains the same as indicated. MC relaxation is 5 days. Tunisia is 7 days.

**Comment by ellykits** [comment]
This functionality has been tested using OPV 2 since its reference date is OPV 1 (This makes it easier for testing since you can vary the ref date of OPV 2 i.e when you gave OPV 1)

Created a kid today (**Wednesday, 13 January 2021**) who is **10 Weeks** old -  **Born Nov 3, 2020** 

Then I gave the vaccine (28 days - 5) days ago which is 23 days ago - Dec 20, 2020
OPV 2 became active in 23 days and not the 28 days defined in the vaccines schedule.

**Comment by AnnieMungai** [comment]
V. 0.0.1-rc3

Looks good to me!
