### ISSUE TITLE
Update Fully Immunized status into Fully Immunized U1 and Fully Immunized U2

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#6]
Note! The immunization schedule and the fully immunized dictionary is [here](https://docs.google.com/spreadsheets/d/1XjdrzwvJ4lm03mp59uyLYAvI-m2RxE0HFNjlDuq9e0w/edit#gid=0). 

- [x] Currently, we have the **Fully immunized** status in the app (see screenshot below) that is displayed when a child receives all the vaccines: BCG, OPV 0 or OPV 4, OPV 1, 2 &3, Penta 1 &2, PCV 1,2 &3, Rota 1&2, MR/Measles 1 & 2. 
![image](https://user-images.githubusercontent.com/58034047/100608914-37045b80-331e-11eb-91ae-6e59c2c15564.png)

The fully immunized status will now be split into 2: - **Fully immunized U1** and **Fully immunized U2** - to see which children have received all of their under 1 (U1) vaccines and all of their under 2 (U2) vaccines.

### Fully immunized U1
- [x] **Fully immunized U1** status should appear for children who are fully immunized with all of the first year vaccines (see list below). 
BCG
OPV 0 or OPV 4
OPV 1
PCV 1
Penta 1
Rota 1
OPV 2
PCV 2
Penta 2
Rota 2
OPV 3
PCV 3
Penta 3
IPV
MR 1
- [x] A child cannot be qualified to be **Fully Immunized U1** if they do not get all the U1 vaccines within their first year of life. 

### Fully immunized U2
- [x] Show the **Fully immunized U2** status for children who have gotten all of the above vaccines plus MR 2. 
- [x] A child's status cannot change to **Fully immunized U2** before being **Fully immunized U1**. 
- [x] 7 days before a child's MR 2 vaccine becomes due, the status will change to `Upcoming 18 months`. The status will then change from upcoming to due ((i.e. Date of MR1 +9 months - 5days) and once  the child receives the MR 2 vaccine, then the status will change to **Fully Immnuzied U2**. 
- [x] A child cannot be qualified as Fully Immunized U2 if they receive MR 2 vaccine after they are 2 years.

**Comment by cafootitt** [comment]
Questions:
- Let's confirm the current formula for `fully immunized` as is currently implemented in the app (i.e. which vaccines does it include?)
- For this issue, I think they want to split `fully immunized` into `U1` and `U2`, right? If so, when would the child's status change from `Fully immunized U1` to "due for Measles 2"?
- Besides this register view screenshot you included above, where else is the status of fully immunized displayed in the app right now?
- Do any of our other immunization apps (Tunisia, Mauritania, Malawi) follow this fully immunized pattern? If so, how do they do it?

**Comment by AnnieMungai** [comment]
@cafootitt I have updated the issue with the discussions held. There are no other immunization apps with this feature. Also for this scope, the change is on the register page. We might need to consider other places in the app that this can be added. cc @rowo

**Comment by cafootitt** [comment]
@AnnieMungai Can you list out the vaccines included in each calculation, so there's no confusion? From the description above, it's not clear whether RR1 is included or not, because it says "up until RR1" which to me sounds like it's not included.

Also, when does Fully immunized U1 status change to "Record 18 months" precisely? On the RR2 due date? Before the due date? We'll have to include explicit instructions here. I would think it should show RR2 is upcoming, but I can't remember when the upcoming period is for the vaccines.

**Comment by AnnieMungai** [comment]
@cafootitt only MC has a logic for fully immunized shown in [this issue](https://github.com/onaio/opensrp-client-wellnesspass/issues/118).

**Comment by cafootitt** [comment]
1. What is the current business logic for the fully immunized status? It would be helpful to know what it currently is, so we can see how we're changing it in this issue.
2. I don't think BCG 2 and OPV 0 and OPV 4 are usually included in fully immunized. Please check the current fully immunized formula and see if these three vaccines are included. Not all children receive or need BCG 2, so we'd end up with a lot of children not fully immunized just because they didn't get BCG 2, which we don't want. Same for OPV 0. Since the immunization window is so small for OPV 0 (only 10 days), this vaccine is usually excluded from the fully immunized formula.
3. Does the MR2 vaccine have an "upcoming" status? Or does it just turn to the blue due status? What is the label you see in the app when MR2 becomes due? Does it say "Record MR2" or does it say "Record xx months"?

**Comment by cafootitt** [comment]
@AnnieMungai Thanks for updating the issue and confirming the business logic. This looks good to me now. I would work with Josphat to write up test cases for this.

**Comment by AnnieMungai** [comment]
v.0.0.4
- [ ] A child got the U1 fully immunized flag even though they got their 9months vaccine when they were older than 1yr (A child MUST get all the under 1 vaccines when they are less than 1 year for them to qualify as Fully Immunized under 1. If a child has gotten all the vaccines required for under 1 but they are older than 1 year, the vaccine status should show the vaccine that is overdue or due next. 
everything else looks good!

**Comment by AnnieMungai** [comment]
v.0.0.5debug
Looks good!
